- name: download node exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
    dest: /opt/
    remote_src: yes
    creates: /opt/node_exporter-0.16.0.linux-amd64
  become: yes

- name: copy node exporter bin
  copy:
    src: /opt/node_exporter-0.16.0.linux-amd64/node_exporter
    dest: /usr/sbin/node_exporter
    mode: 0755
    remote_src: yes
  become: yes

- include: upstart.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- include: systemd.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'
